[package]
name = "lite-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client={path = "deps/solana/client"}
solana-sdk={path = "deps/solana/sdk"}
tokio = { version = "1.14.1", features = ["full"]}
futures = "0.3.25"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0" }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
solana-rpc = {path = "deps/solana/rpc"}
clap = "2.33.1"
solana-clap-utils = { path = "deps/solana/clap-utils" }
solana-cli-config = { path = "deps/solana/cli-config" }
solana-pubsub-client = { path = "deps/solana/pubsub-client" }

base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "4.0.2"
itertools = "0.10.5"
libc = "0.2.131"
log = "0.4.17"
rayon = "1.5.3"
regex = "1.6.0"
serde = "1.0.144"
serde_derive = "1.0.103"
serde_json = "1.0.83"
soketto = "0.7"
solana-account-decoder = { path = "deps/solana/account-decoder", version = "=1.15.0" }
solana-entry = { path = "deps/solana/entry", version = "=1.15.0" }
solana-faucet = { path = "deps/solana/faucet", version = "=1.15.0" }
solana-gossip = { path = "deps/solana/gossip", version = "=1.15.0" }
solana-ledger = { path = "deps/solana/ledger", version = "=1.15.0" }
solana-measure = { path = "deps/solana/measure", version = "=1.15.0" }
solana-metrics = { path = "deps/solana/metrics", version = "=1.15.0" }
solana-perf = { path = "deps/solana/perf", version = "=1.15.0" }
solana-poh = { path = "deps/solana/poh", version = "=1.15.0" }
solana-rayon-threadlimit = { path = "deps/solana/rayon-threadlimit", version = "=1.15.0" }
solana-rpc-client-api = { path = "deps/solana/rpc-client-api", version = "=1.15.0" }
solana-runtime = { path = "deps/solana/runtime", version = "=1.15.0" }
solana-send-transaction-service = { path = "deps/solana/send-transaction-service", version = "=1.15.0" }
solana-stake-program = { path = "deps/solana/programs/stake", version = "=1.15.0" }
solana-storage-bigtable = { path = "deps/solana/storage-bigtable", version = "=1.15.0" }
solana-streamer = { path = "deps/solana/streamer", version = "=1.15.0" }
solana-tpu-client = { path = "deps/solana/tpu-client", version = "=1.15.0", default-features = false }
solana-transaction-status = { path = "deps/solana/transaction-status", version = "=1.15.0" }
solana-version = { path = "deps/solana/version", version = "=1.15.0" }
solana-vote-program = { path = "deps/solana/programs/vote", version = "=1.15.0" }
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "=0.4.3", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
csv = "1.1.6"
serde = { version = "1", features = ["derive"]}

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
